#!/usr/bin/env bash
# Auto-generated by scripts/generate_orca_experiments.py.
# Resumable: re-run to execute only the runs missing a completed
# phase1_evaluation/phase1_evaluation_results.json. Continues past
# individual failures instead of aborting the whole grid.
set -uo pipefail

FAILED=()
SKIPPED=()

echo "=== ER-NOONTW__cnamuangtoun__s13 ==="
if [ -f "results/research_runs/ER-NOONTW__cnamuangtoun__s13/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTW__cnamuangtoun__s13: results/research_runs/ER-NOONTW__cnamuangtoun__s13/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTW__cnamuangtoun__s13")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTW__cnamuangtoun__s13/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s13/phase1_pretraining --variant denominator --seed 13 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTW__cnamuangtoun__s13/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTW__cnamuangtoun__s13/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s13/phase1_evaluation; then
    echo "  [ok]   ER-NOONTW__cnamuangtoun__s13"
  else
    echo "  [FAIL] ER-NOONTW__cnamuangtoun__s13"
    FAILED+=("ER-NOONTW__cnamuangtoun__s13")
  fi
fi

echo "=== ER-NOONTW__cnamuangtoun__s21 ==="
if [ -f "results/research_runs/ER-NOONTW__cnamuangtoun__s21/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTW__cnamuangtoun__s21: results/research_runs/ER-NOONTW__cnamuangtoun__s21/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTW__cnamuangtoun__s21")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTW__cnamuangtoun__s21/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s21/phase1_pretraining --variant denominator --seed 21 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTW__cnamuangtoun__s21/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTW__cnamuangtoun__s21/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s21/phase1_evaluation; then
    echo "  [ok]   ER-NOONTW__cnamuangtoun__s21"
  else
    echo "  [FAIL] ER-NOONTW__cnamuangtoun__s21"
    FAILED+=("ER-NOONTW__cnamuangtoun__s21")
  fi
fi

echo "=== ER-NOONTW__cnamuangtoun__s42 ==="
if [ -f "results/research_runs/ER-NOONTW__cnamuangtoun__s42/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTW__cnamuangtoun__s42: results/research_runs/ER-NOONTW__cnamuangtoun__s42/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTW__cnamuangtoun__s42")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTW__cnamuangtoun__s42/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s42/phase1_pretraining --variant denominator --seed 42 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTW__cnamuangtoun__s42/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTW__cnamuangtoun__s42/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s42/phase1_evaluation; then
    echo "  [ok]   ER-NOONTW__cnamuangtoun__s42"
  else
    echo "  [FAIL] ER-NOONTW__cnamuangtoun__s42"
    FAILED+=("ER-NOONTW__cnamuangtoun__s42")
  fi
fi

echo "=== ER-NOONTW__cnamuangtoun__s87 ==="
if [ -f "results/research_runs/ER-NOONTW__cnamuangtoun__s87/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTW__cnamuangtoun__s87: results/research_runs/ER-NOONTW__cnamuangtoun__s87/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTW__cnamuangtoun__s87")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTW__cnamuangtoun__s87/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s87/phase1_pretraining --variant denominator --seed 87 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTW__cnamuangtoun__s87/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTW__cnamuangtoun__s87/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s87/phase1_evaluation; then
    echo "  [ok]   ER-NOONTW__cnamuangtoun__s87"
  else
    echo "  [FAIL] ER-NOONTW__cnamuangtoun__s87"
    FAILED+=("ER-NOONTW__cnamuangtoun__s87")
  fi
fi

echo "=== ER-NOONTW__cnamuangtoun__s123 ==="
if [ -f "results/research_runs/ER-NOONTW__cnamuangtoun__s123/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTW__cnamuangtoun__s123: results/research_runs/ER-NOONTW__cnamuangtoun__s123/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTW__cnamuangtoun__s123")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTW__cnamuangtoun__s123/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s123/phase1_pretraining --variant denominator --seed 123 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTW__cnamuangtoun__s123/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTW__cnamuangtoun__s123/training_config.json --output-dir results/research_runs/ER-NOONTW__cnamuangtoun__s123/phase1_evaluation; then
    echo "  [ok]   ER-NOONTW__cnamuangtoun__s123"
  else
    echo "  [FAIL] ER-NOONTW__cnamuangtoun__s123"
    FAILED+=("ER-NOONTW__cnamuangtoun__s123")
  fi
fi

echo "=== ER-NOONTALL__cnamuangtoun__s13 ==="
if [ -f "results/research_runs/ER-NOONTALL__cnamuangtoun__s13/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTALL__cnamuangtoun__s13: results/research_runs/ER-NOONTALL__cnamuangtoun__s13/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTALL__cnamuangtoun__s13")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTALL__cnamuangtoun__s13/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s13/phase1_pretraining --variant denominator --seed 13 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTALL__cnamuangtoun__s13/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTALL__cnamuangtoun__s13/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s13/phase1_evaluation; then
    echo "  [ok]   ER-NOONTALL__cnamuangtoun__s13"
  else
    echo "  [FAIL] ER-NOONTALL__cnamuangtoun__s13"
    FAILED+=("ER-NOONTALL__cnamuangtoun__s13")
  fi
fi

echo "=== ER-NOONTALL__cnamuangtoun__s21 ==="
if [ -f "results/research_runs/ER-NOONTALL__cnamuangtoun__s21/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTALL__cnamuangtoun__s21: results/research_runs/ER-NOONTALL__cnamuangtoun__s21/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTALL__cnamuangtoun__s21")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTALL__cnamuangtoun__s21/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s21/phase1_pretraining --variant denominator --seed 21 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTALL__cnamuangtoun__s21/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTALL__cnamuangtoun__s21/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s21/phase1_evaluation; then
    echo "  [ok]   ER-NOONTALL__cnamuangtoun__s21"
  else
    echo "  [FAIL] ER-NOONTALL__cnamuangtoun__s21"
    FAILED+=("ER-NOONTALL__cnamuangtoun__s21")
  fi
fi

echo "=== ER-NOONTALL__cnamuangtoun__s42 ==="
if [ -f "results/research_runs/ER-NOONTALL__cnamuangtoun__s42/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTALL__cnamuangtoun__s42: results/research_runs/ER-NOONTALL__cnamuangtoun__s42/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTALL__cnamuangtoun__s42")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTALL__cnamuangtoun__s42/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s42/phase1_pretraining --variant denominator --seed 42 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTALL__cnamuangtoun__s42/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTALL__cnamuangtoun__s42/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s42/phase1_evaluation; then
    echo "  [ok]   ER-NOONTALL__cnamuangtoun__s42"
  else
    echo "  [FAIL] ER-NOONTALL__cnamuangtoun__s42"
    FAILED+=("ER-NOONTALL__cnamuangtoun__s42")
  fi
fi

echo "=== ER-NOONTALL__cnamuangtoun__s87 ==="
if [ -f "results/research_runs/ER-NOONTALL__cnamuangtoun__s87/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTALL__cnamuangtoun__s87: results/research_runs/ER-NOONTALL__cnamuangtoun__s87/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTALL__cnamuangtoun__s87")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTALL__cnamuangtoun__s87/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s87/phase1_pretraining --variant denominator --seed 87 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTALL__cnamuangtoun__s87/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTALL__cnamuangtoun__s87/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s87/phase1_evaluation; then
    echo "  [ok]   ER-NOONTALL__cnamuangtoun__s87"
  else
    echo "  [FAIL] ER-NOONTALL__cnamuangtoun__s87"
    FAILED+=("ER-NOONTALL__cnamuangtoun__s87")
  fi
fi

echo "=== ER-NOONTALL__cnamuangtoun__s123 ==="
if [ -f "results/research_runs/ER-NOONTALL__cnamuangtoun__s123/phase1_evaluation/phase1_evaluation_results.json" ]; then
  echo "  [skip] ER-NOONTALL__cnamuangtoun__s123: results/research_runs/ER-NOONTALL__cnamuangtoun__s123/phase1_evaluation/phase1_evaluation_results.json already exists"
  SKIPPED+=("ER-NOONTALL__cnamuangtoun__s123")
else
  if python run_orca_training.py --train-file preprocess/data_splits_v7/train.jsonl --validation-file preprocess/data_splits_v7/validation.jsonl --config results/research_runs/ER-NOONTALL__cnamuangtoun__s123/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s123/phase1_pretraining --variant denominator --seed 123 --require-ontology && python run_phase1_embedding_evaluation.py --dataset preprocess/data_splits_v7/test.jsonl --checkpoint results/research_runs/ER-NOONTALL__cnamuangtoun__s123/phase1_pretraining/best_checkpoint.pt --config results/research_runs/ER-NOONTALL__cnamuangtoun__s123/training_config.json --output-dir results/research_runs/ER-NOONTALL__cnamuangtoun__s123/phase1_evaluation; then
    echo "  [ok]   ER-NOONTALL__cnamuangtoun__s123"
  else
    echo "  [FAIL] ER-NOONTALL__cnamuangtoun__s123"
    FAILED+=("ER-NOONTALL__cnamuangtoun__s123")
  fi
fi

echo ""
echo "=== ORCA grid summary ==="
echo "Skipped (already complete): ${#SKIPPED[@]}"
echo "Failed: ${#FAILED[@]}"
if [ ${#FAILED[@]} -gt 0 ]; then
  printf "  - %s\n" "${FAILED[@]}"
  exit 1
fi
